/**
 * Independent Living Skills (ILS) Seed Data - Part 2
 * Transportation & Housing/Home Care skills
 */

import { ILSDomain } from './seed-ils-skills-part1';

// Transportation Skills (10 skills)
export const transportationSkills = [
  {
    name: 'Reading a Bus Schedule',
    description: 'Locate bus times and routes on a schedule',
    domain: ILSDomain.TRANSPORTATION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Find route number', promptHierarchy: ['VERBAL', 'GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Locate starting stop', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Find destination stop', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Read departure time', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Read arrival time', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['CLASSROOM', 'COMMUNITY_TRANSPORT'],
    materialsNeeded: ['Bus schedule', 'Highlighter'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Riding Public Bus',
    description: 'Complete a bus trip from start to destination',
    domain: ILSDomain.TRANSPORTATION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Wait at correct bus stop', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Signal bus to stop', promptHierarchy: ['MODEL', 'GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Board and pay fare', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Find seat or hold rail', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 5, description: 'Watch for destination', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Pull cord to request stop', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Exit safely when bus stops', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['COMMUNITY_TRANSPORT'],
    materialsNeeded: ['Bus fare/pass', 'Route map'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Pedestrian Safety - Crosswalk',
    description: 'Cross street safely at crosswalk',
    domain: ILSDomain.TRANSPORTATION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Stop at curb', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Look for crosswalk signal', promptHierarchy: ['GESTURAL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Wait for walk signal', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 4, description: 'Look left-right-left', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 5, description: 'Walk, don\'t run', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Stay in crosswalk', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 8, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['CLASSROOM', 'COMMUNITY_OTHER'],
    materialsNeeded: ['Practice area or simulation'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Using GPS/Maps App',
    description: 'Navigate using smartphone maps application',
    domain: ILSDomain.TRANSPORTATION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Open maps app', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Enter destination', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Select transportation mode', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Start navigation', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Follow directions', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['CLASSROOM', 'COMMUNITY_OTHER'],
    materialsNeeded: ['Smartphone with maps app'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Calling Taxi/Rideshare',
    description: 'Request ride using app or phone',
    domain: ILSDomain.TRANSPORTATION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Open rideshare app', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Enter pickup location', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Enter destination', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Confirm price/request ride', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Wait at safe location', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 6, description: 'Verify driver and car', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 7, description: 'Get in and wear seatbelt', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 16, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['COMMUNITY_OTHER'],
    materialsNeeded: ['Smartphone with rideshare app'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Reading Street Signs',
    description: 'Identify and understand common street signs',
    domain: ILSDomain.TRANSPORTATION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Look for signs', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Identify sign type by shape/color', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Read sign text or symbol', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Respond appropriately', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['CLASSROOM', 'COMMUNITY_OTHER'],
    materialsNeeded: ['Street sign flashcards', 'Community walk'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Planning a Trip Route',
    description: 'Plan multi-step journey using maps',
    domain: ILSDomain.TRANSPORTATION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Identify starting point', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Identify destination', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Find possible routes', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Consider time and transfers', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Choose best route', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Write down or save directions', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['CLASSROOM', 'HOME'],
    materialsNeeded: ['Maps app or transit website'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Using Subway/Metro',
    description: 'Navigate subway system independently',
    domain: ILSDomain.TRANSPORTATION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Find correct station entrance', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Purchase ticket/tap card', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Go through turnstile', promptHierarchy: ['MODEL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Find correct platform', promptHierarchy: ['VERBAL', 'GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Stand behind safety line', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 6, description: 'Board train when doors open', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Exit at correct stop', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 4,
    targetSettings: ['COMMUNITY_TRANSPORT'],
    materialsNeeded: ['Transit card', 'Subway map'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Bicycle Safety',
    description: 'Ride bicycle safely on roads and paths',
    domain: ILSDomain.TRANSPORTATION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Wear helmet properly', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Check bike before riding', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Stay on right side', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Signal turns', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Obey traffic signs', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 6, description: 'Watch for hazards', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['COMMUNITY_OTHER', 'COMMUNITY_RECREATION'],
    materialsNeeded: ['Bicycle', 'Helmet'],
    isCriticalSafety: true, communityRelevance: 4, employmentRelevance: 3,
  },
  {
    name: 'Asking for Directions',
    description: 'Appropriately ask for help finding location',
    domain: ILSDomain.TRANSPORTATION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Identify safe person to ask', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Approach politely', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'State where you need to go', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Listen to directions', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 5, description: 'Repeat back or ask to clarify', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Thank the person', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['COMMUNITY_OTHER', 'COMMUNITY_STORE'],
    materialsNeeded: ['Role play scenarios'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 4,
  },
];

// Housing & Home Care Skills (10 skills)
export const housingHomeCareSkills = [
  {
    name: 'Sorting Laundry',
    description: 'Sort laundry by color and fabric type',
    domain: ILSDomain.HOUSING_HOME_CARE,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Get laundry basket', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 2, description: 'Set up sorting bins', promptHierarchy: ['VERBAL', 'GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Pick up each item', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Check color', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Place in correct bin', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'COMMUNITY_OTHER'],
    materialsNeeded: ['Laundry basket', 'Sorting bins'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 3,
  },
  {
    name: 'Using Washer',
    description: 'Operate washing machine to clean clothes',
    domain: ILSDomain.HOUSING_HOME_CARE,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Load clothes (not overfilled)', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Add detergent in correct spot', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Close door/lid', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Select water temp and cycle', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Start machine', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Wait for cycle to complete', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 7, description: 'Remove clothes promptly', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'COMMUNITY_OTHER'],
    materialsNeeded: ['Washing machine', 'Detergent', 'Clothes'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Using Dryer',
    description: 'Operate dryer to dry clothes',
    domain: ILSDomain.HOUSING_HOME_CARE,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Clean lint trap', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Load wet clothes', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Close door', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Select heat setting', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Set time or cycle', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Start dryer', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Remove and fold when done', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'COMMUNITY_OTHER'],
    materialsNeeded: ['Dryer', 'Wet clothes'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Making a Bed',
    description: 'Make bed neatly with sheets and blankets',
    domain: ILSDomain.HOUSING_HOME_CARE,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Remove pillows', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 2, description: 'Straighten fitted sheet', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Spread flat sheet evenly', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Tuck in sides', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Add blanket/comforter', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Replace pillows', promptHierarchy: ['INDEPENDENT'] },
    ],
    ageAppropriateStart: 8, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'CLASSROOM'],
    materialsNeeded: ['Bed', 'Sheets', 'Blanket', 'Pillows'],
    isCriticalSafety: false, communityRelevance: 4, employmentRelevance: 3,
  },
  {
    name: 'Vacuuming',
    description: 'Vacuum carpets and rugs effectively',
    domain: ILSDomain.HOUSING_HOME_CARE,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Clear floor of objects', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Plug in vacuum', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Turn on vacuum', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Push/pull in straight lines', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Cover entire floor area', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Turn off and unplug', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Store vacuum properly', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'CLASSROOM', 'COMMUNITY_WORKPLACE'],
    materialsNeeded: ['Vacuum cleaner'],
    isCriticalSafety: false, communityRelevance: 4, employmentRelevance: 4,
  },
  {
    name: 'Washing Dishes by Hand',
    description: 'Clean dishes in sink properly',
    domain: ILSDomain.HOUSING_HOME_CARE,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Scrape food into trash', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Fill sink with warm soapy water', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Wash each dish with sponge', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Rinse under clean water', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Place in drying rack', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Drain sink and wipe counters', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'SCHOOL_CAFETERIA', 'COMMUNITY_WORKPLACE'],
    materialsNeeded: ['Sink', 'Dish soap', 'Sponge', 'Drying rack'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Loading Dishwasher',
    description: 'Properly load and run dishwasher',
    domain: ILSDomain.HOUSING_HOME_CARE,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Scrape food off dishes', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Load plates in bottom rack', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Load glasses in top rack', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Load silverware in basket', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Add detergent', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Select cycle and start', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME'],
    materialsNeeded: ['Dishwasher', 'Detergent', 'Dirty dishes'],
    isCriticalSafety: false, communityRelevance: 4, employmentRelevance: 3,
  },
  {
    name: 'Cleaning Bathroom',
    description: 'Clean toilet, sink, and surfaces',
    domain: ILSDomain.HOUSING_HOME_CARE,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Gather cleaning supplies', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Spray cleaner on surfaces', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Wipe sink and counter', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Clean toilet with brush', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Wipe toilet exterior', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Clean mirror', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Wash hands thoroughly', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['HOME', 'COMMUNITY_WORKPLACE'],
    materialsNeeded: ['Cleaning spray', 'Toilet brush', 'Paper towels', 'Gloves'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Taking Out Trash',
    description: 'Empty trash and replace bag',
    domain: ILSDomain.HOUSING_HOME_CARE,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Lift bag from can', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 2, description: 'Tie bag closed', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Carry to outdoor bin', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Place in bin', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 5, description: 'Get new bag for can', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Place new bag in can', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 8, ageAppropriateEnd: 22, difficultyLevel: 1,
    targetSettings: ['HOME', 'CLASSROOM', 'COMMUNITY_WORKPLACE'],
    materialsNeeded: ['Trash bags'],
    isCriticalSafety: false, communityRelevance: 4, employmentRelevance: 4,
  },
  {
    name: 'Basic Home Repairs',
    description: 'Complete simple maintenance tasks',
    domain: ILSDomain.HOUSING_HOME_CARE,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Identify the problem', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Gather needed tools', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Follow repair steps', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Test the repair', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Clean up and put tools away', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 4,
    targetSettings: ['HOME', 'CLASSROOM'],
    materialsNeeded: ['Basic tool kit'],
    isCriticalSafety: true, communityRelevance: 4, employmentRelevance: 4,
  },
];

// Export all skills from this file
export const ilsSkillsPart2 = [
  ...transportationSkills,
  ...housingHomeCareSkills,
];

console.log(`ILS Seeds Part 2: ${transportationSkills.length} Transportation + ${housingHomeCareSkills.length} Housing = ${ilsSkillsPart2.length} total skills`);
