/**
 * Independent Living Skills (ILS) Seed Data - Part 3
 * Health & Safety and Community Resources skills
 */

import { ILSDomain } from './seed-ils-skills-part1';

// Health & Safety Skills (10 skills)
export const healthSafetySkills = [
  {
    name: 'Handwashing',
    description: 'Wash hands properly with soap and water',
    domain: ILSDomain.HEALTH_SAFETY,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Turn on water', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 2, description: 'Wet hands', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Apply soap', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Rub hands together 20 seconds', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Scrub between fingers', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Rinse thoroughly', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 7, description: 'Dry with clean towel', promptHierarchy: ['INDEPENDENT'] },
    ],
    ageAppropriateStart: 4, ageAppropriateEnd: 12, difficultyLevel: 1,
    targetSettings: ['HOME', 'CLASSROOM', 'COMMUNITY_RESTAURANT'],
    materialsNeeded: ['Sink', 'Soap', 'Towel'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Brushing Teeth',
    description: 'Brush teeth thoroughly twice daily',
    domain: ILSDomain.HEALTH_SAFETY,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Get toothbrush and toothpaste', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Apply pea-sized toothpaste', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Brush outer surfaces', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Brush inner surfaces', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Brush chewing surfaces', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Brush tongue', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Rinse and spit', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 8, description: 'Rinse toothbrush and store', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 4, ageAppropriateEnd: 12, difficultyLevel: 2,
    targetSettings: ['HOME'],
    materialsNeeded: ['Toothbrush', 'Toothpaste', 'Cup'],
    isCriticalSafety: false, communityRelevance: 4, employmentRelevance: 4,
  },
  {
    name: 'Calling 911',
    description: 'Recognize emergencies and call for help',
    domain: ILSDomain.HEALTH_SAFETY,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Recognize emergency situation', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Find phone', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Dial 911', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Stay calm and speak clearly', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'State your emergency', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Give your location', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 7, description: 'Stay on line until told to hang up', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 8, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['CLASSROOM', 'HOME'],
    materialsNeeded: ['Practice phone', 'Emergency scenarios'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Taking Medication',
    description: 'Take prescribed medication correctly',
    domain: ILSDomain.HEALTH_SAFETY,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Check medication name', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Check dosage amount', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 3, description: 'Check time to take', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Get water', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 5, description: 'Take correct amount', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 6, description: 'Record that you took it', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['HOME', 'CLASSROOM'],
    materialsNeeded: ['Medication organizer', 'Tracking chart'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'First Aid - Minor Cuts',
    description: 'Clean and bandage small cuts',
    domain: ILSDomain.HEALTH_SAFETY,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Wash hands first', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Rinse cut under clean water', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Apply gentle pressure if bleeding', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Apply antibiotic ointment', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Cover with bandage', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Tell adult if it doesn\'t stop bleeding', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'CLASSROOM'],
    materialsNeeded: ['First aid kit', 'Bandages', 'Antibiotic ointment'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Fire Safety - Exit',
    description: 'Safely exit building during fire alarm',
    domain: ILSDomain.HEALTH_SAFETY,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Stop what you\'re doing', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Stay calm', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Go to nearest exit', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 4, description: 'Feel door before opening', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Stay low if smoke', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 6, description: 'Go to meeting point', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Do not go back inside', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 6, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['CLASSROOM', 'HOME', 'COMMUNITY_OTHER'],
    materialsNeeded: ['Fire drill practice', 'Exit route maps'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Showering/Bathing',
    description: 'Complete personal hygiene routine',
    domain: ILSDomain.HEALTH_SAFETY,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Gather supplies', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Adjust water temperature', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 3, description: 'Wet body completely', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Apply soap/body wash', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Wash all body areas', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Rinse completely', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 7, description: 'Turn off water', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 8, description: 'Dry off completely', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 8, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME'],
    materialsNeeded: ['Soap', 'Shampoo', 'Towel', 'Washcloth'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Using Public Restroom',
    description: 'Use public restroom appropriately',
    domain: ILSDomain.HEALTH_SAFETY,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Find appropriate restroom', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Enter and lock stall', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Use toilet', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Use toilet paper', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 5, description: 'Flush toilet', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Unlock and exit stall', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 7, description: 'Wash hands thoroughly', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 6, ageAppropriateEnd: 14, difficultyLevel: 2,
    targetSettings: ['COMMUNITY_STORE', 'COMMUNITY_RESTAURANT', 'COMMUNITY_RECREATION'],
    materialsNeeded: ['Practice in safe community locations'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Recognizing Illness Symptoms',
    description: 'Identify when feeling sick and communicate',
    domain: ILSDomain.HEALTH_SAFETY,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Notice how body feels', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Identify symptoms', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Tell trusted adult', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 4, description: 'Describe symptoms clearly', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Follow care instructions', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 6, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'CLASSROOM'],
    materialsNeeded: ['Body chart', 'Symptom cards'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Stranger Safety',
    description: 'Recognize and respond to unsafe situations',
    domain: ILSDomain.HEALTH_SAFETY,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Identify trusted vs unknown people', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Keep safe distance from strangers', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Say no to unwanted contact', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 4, description: 'Go to safe place', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 5, description: 'Tell trusted adult', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 6, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['CLASSROOM', 'COMMUNITY_OTHER'],
    materialsNeeded: ['Safety scenarios', 'Role play materials'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
];

// Community Resources Skills (10 skills)
export const communityResourcesSkills = [
  {
    name: 'Using Library',
    description: 'Navigate library and check out materials',
    domain: ILSDomain.COMMUNITY_RESOURCES,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Enter library quietly', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Find desired section', promptHierarchy: ['VERBAL', 'GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Select materials', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Go to checkout desk', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Present library card', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Wait for items to be scanned', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 7, description: 'Note due date', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 8, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['COMMUNITY_LIBRARY'],
    materialsNeeded: ['Library card'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 3,
  },
  {
    name: 'Grocery Shopping',
    description: 'Complete grocery shopping independently',
    domain: ILSDomain.COMMUNITY_RESOURCES,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Make shopping list', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Get shopping cart/basket', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Find items on list', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Check prices', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Go to checkout', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 6, description: 'Place items on belt', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 7, description: 'Pay and bag items', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['COMMUNITY_STORE'],
    materialsNeeded: ['Shopping list', 'Money/card'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Ordering at Restaurant',
    description: 'Order food at fast food or sit-down restaurant',
    domain: ILSDomain.COMMUNITY_RESOURCES,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Wait to be seated or approach counter', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Look at menu', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Decide what to order', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Tell server/cashier order', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Answer any questions', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Pay for food', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Say thank you', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['COMMUNITY_RESTAURANT'],
    materialsNeeded: ['Money/card', 'Practice menus'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Using Post Office',
    description: 'Mail letters and packages',
    domain: ILSDomain.COMMUNITY_RESOURCES,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Address envelope/package correctly', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Go to post office', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Wait in line', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Tell clerk what you need', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Pay for postage', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Get receipt if needed', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['COMMUNITY_GOVERNMENT'],
    materialsNeeded: ['Mail item', 'Money'],
    isCriticalSafety: false, communityRelevance: 4, employmentRelevance: 3,
  },
  {
    name: 'Making Doctor Appointment',
    description: 'Call and schedule medical appointment',
    domain: ILSDomain.COMMUNITY_RESOURCES,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Find doctor\'s phone number', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Call during office hours', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'State you need appointment', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Provide your information', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'State reason for visit', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Agree on date/time', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Write down appointment', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 16, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['HOME', 'CLASSROOM'],
    materialsNeeded: ['Phone', 'Calendar', 'Doctor info'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Using Bank Services',
    description: 'Conduct basic banking transactions',
    domain: ILSDomain.COMMUNITY_RESOURCES,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Enter bank and get in line', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Fill out deposit/withdrawal slip', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Approach teller when called', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'State transaction needed', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Provide ID and account info', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Verify transaction', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Take receipt and money', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 16, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['COMMUNITY_BANK'],
    materialsNeeded: ['Bank account', 'ID', 'Deposit slip'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Voting',
    description: 'Register to vote and cast ballot',
    domain: ILSDomain.COMMUNITY_RESOURCES,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Register to vote', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Find polling location', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Go on election day', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Show ID if required', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Get ballot', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 6, description: 'Mark choices clearly', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Submit ballot', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 18, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['COMMUNITY_GOVERNMENT'],
    materialsNeeded: ['Voter registration', 'ID', 'Sample ballot'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 2,
  },
  {
    name: 'Applying for ID/License',
    description: 'Apply for state ID or driver\'s license',
    domain: ILSDomain.COMMUNITY_RESOURCES,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Gather required documents', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Go to DMV', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Take number and wait', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Complete application form', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Provide documents', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Pay fee', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 7, description: 'Take photo', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 16, ageAppropriateEnd: 22, difficultyLevel: 4,
    targetSettings: ['COMMUNITY_GOVERNMENT'],
    materialsNeeded: ['Birth certificate', 'Social security card', 'Proof of address'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Filling Out Forms',
    description: 'Complete common application forms',
    domain: ILSDomain.COMMUNITY_RESOURCES,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Read instructions', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Fill in personal info', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Answer all questions', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Check for errors', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Sign and date', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['CLASSROOM', 'HOME'],
    materialsNeeded: ['Practice forms', 'Personal info reference'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Using Recreation Center',
    description: 'Access and use community recreation facilities',
    domain: ILSDomain.COMMUNITY_RESOURCES,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Check membership or fees', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Enter and check in', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Find desired activity area', promptHierarchy: ['VERBAL', 'GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Follow facility rules', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Use equipment safely', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Clean up after use', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['COMMUNITY_RECREATION'],
    materialsNeeded: ['Membership card', 'Appropriate attire'],
    isCriticalSafety: false, communityRelevance: 4, employmentRelevance: 2,
  },
];

// Export all skills from this file
export const ilsSkillsPart3 = [
  ...healthSafetySkills,
  ...communityResourcesSkills,
];

console.log(`ILS Seeds Part 3: ${healthSafetySkills.length} Health/Safety + ${communityResourcesSkills.length} Community = ${ilsSkillsPart3.length} total skills`);
