/**
 * Independent Living Skills (ILS) Seed Data - Part 1
 * Money Management & Cooking/Nutrition skills
 * 
 * Run after: pnpm prisma generate
 */

// Domain constants (matches Prisma schema)
export const ILSDomain = {
  MONEY_MANAGEMENT: 'MONEY_MANAGEMENT',
  COOKING_NUTRITION: 'COOKING_NUTRITION',
  TRANSPORTATION: 'TRANSPORTATION',
  HOUSING_HOME_CARE: 'HOUSING_HOME_CARE',
  HEALTH_SAFETY: 'HEALTH_SAFETY',
  COMMUNITY_RESOURCES: 'COMMUNITY_RESOURCES',
} as const;

// Money Management Skills (10 skills)
export const moneyManagementSkills = [
  {
    name: 'Identifying Coins',
    description: 'Recognize and name penny, nickel, dime, and quarter',
    domain: ILSDomain.MONEY_MANAGEMENT,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Pick up coin', promptHierarchy: ['FULL_PHYSICAL', 'GESTURAL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Look at size and color', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Name the coin correctly', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 5, ageAppropriateEnd: 12, difficultyLevel: 1,
    targetSettings: ['CLASSROOM', 'HOME', 'COMMUNITY_STORE'],
    materialsNeeded: ['Real coins', 'Coin sorting tray'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Counting Coins to $1.00',
    description: 'Count mixed coins up to one dollar',
    domain: ILSDomain.MONEY_MANAGEMENT,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Sort coins by type', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Count quarters first', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Add dimes to total', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Add nickels to total', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Add pennies to total', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 6, description: 'State total amount', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 7, ageAppropriateEnd: 14, difficultyLevel: 2,
    targetSettings: ['CLASSROOM', 'HOME', 'COMMUNITY_STORE'],
    materialsNeeded: ['Mixed coins', 'Counting mat'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Identifying Dollar Bills',
    description: 'Recognize $1, $5, $10, and $20 bills',
    domain: ILSDomain.MONEY_MANAGEMENT,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Pick up bill', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 2, description: 'Look at number in corner', promptHierarchy: ['GESTURAL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'State denomination', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 6, ageAppropriateEnd: 14, difficultyLevel: 1,
    targetSettings: ['CLASSROOM', 'HOME', 'COMMUNITY_BANK'],
    materialsNeeded: ['Sample bills or play money'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Using a Vending Machine',
    description: 'Select item, insert money, and retrieve purchase',
    domain: ILSDomain.MONEY_MANAGEMENT,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Read prices on items', promptHierarchy: ['GESTURAL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Select desired item', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Insert correct amount', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Press selection button', promptHierarchy: ['MODEL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Retrieve item and change', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['SCHOOL_COMMON', 'COMMUNITY_RECREATION'],
    materialsNeeded: ['Vending machine access', 'Coins/bills'],
    isCriticalSafety: false, communityRelevance: 4, employmentRelevance: 3,
  },
  {
    name: 'Using Debit Card',
    description: 'Complete purchase using debit card at point of sale',
    domain: ILSDomain.MONEY_MANAGEMENT,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Wait for cashier prompt', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Insert/swipe/tap card', promptHierarchy: ['MODEL', 'GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Enter PIN privately', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Confirm amount', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Remove card and take receipt', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['COMMUNITY_STORE', 'COMMUNITY_RESTAURANT'],
    materialsNeeded: ['Practice debit card'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Using an ATM',
    description: 'Withdraw cash from ATM machine safely',
    domain: ILSDomain.MONEY_MANAGEMENT,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Check surroundings for safety', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Insert card', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Enter PIN privately', promptHierarchy: ['INDEPENDENT'], criticalStep: true },
      { stepNumber: 4, description: 'Select withdrawal and amount', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Take card, cash, receipt', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Put money away before leaving', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 16, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['COMMUNITY_BANK'],
    materialsNeeded: ['ATM access or simulator'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Creating Simple Budget',
    description: 'Allocate income to basic expense categories',
    domain: ILSDomain.MONEY_MANAGEMENT,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Identify income amount', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'List essential expenses', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Subtract essentials from income', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Allocate savings amount', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 4,
    targetSettings: ['CLASSROOM', 'HOME'],
    materialsNeeded: ['Budget worksheet', 'Calculator'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Reading a Pay Stub',
    description: 'Understand components of a paycheck stub',
    domain: ILSDomain.MONEY_MANAGEMENT,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Locate gross pay', promptHierarchy: ['GESTURAL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Find deductions section', promptHierarchy: ['GESTURAL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Locate net pay (take-home)', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Verify hours worked', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 16, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['CLASSROOM', 'COMMUNITY_WORKPLACE'],
    materialsNeeded: ['Sample pay stubs'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
  {
    name: 'Comparing Prices',
    description: 'Compare unit prices to find best value',
    domain: ILSDomain.MONEY_MANAGEMENT,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Find price tags', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Locate unit price', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Compare unit prices', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Select best value', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['COMMUNITY_STORE'],
    materialsNeeded: ['Store price tags', 'Calculator'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 3,
  },
  {
    name: 'Making Change',
    description: 'Calculate and count back change',
    domain: ILSDomain.MONEY_MANAGEMENT,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Identify cost of item', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Subtract from amount paid', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Select correct coins/bills', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Count back change', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 18, difficultyLevel: 3,
    targetSettings: ['CLASSROOM', 'COMMUNITY_STORE', 'COMMUNITY_WORKPLACE'],
    materialsNeeded: ['Coins and bills', 'Practice items'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 5,
  },
];

// Cooking & Nutrition Skills (10 skills)
export const cookingNutritionSkills = [
  {
    name: 'Making a Sandwich',
    description: 'Prepare a simple sandwich independently',
    domain: ILSDomain.COOKING_NUTRITION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Gather ingredients', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Get two slices of bread', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Apply condiment', promptHierarchy: ['GESTURAL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Add protein/filling', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Add toppings', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 6, description: 'Place top bread', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 7, description: 'Cut if desired', promptHierarchy: ['MODEL', 'INDEPENDENT'] },
      { stepNumber: 8, description: 'Clean up workspace', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 8, ageAppropriateEnd: 18, difficultyLevel: 2,
    targetSettings: ['HOME', 'SCHOOL_CAFETERIA'],
    materialsNeeded: ['Bread', 'Knife', 'Cutting board', 'Fillings'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 3,
  },
  {
    name: 'Using Microwave',
    description: 'Safely heat food in microwave',
    domain: ILSDomain.COOKING_NUTRITION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Place food in microwave-safe container', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Open microwave door', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Place food inside, close door', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Set time', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Press start', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 6, description: 'Wait for beep', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 7, description: 'Carefully remove hot food', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'SCHOOL_CAFETERIA', 'COMMUNITY_WORKPLACE'],
    materialsNeeded: ['Microwave', 'Microwave-safe containers'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Pouring Beverage',
    description: 'Pour beverage from container to glass safely',
    domain: ILSDomain.COOKING_NUTRITION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Get glass and beverage', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Place glass on stable surface', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Hold container with both hands', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Pour slowly watching level', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Stop before overflow', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 6, ageAppropriateEnd: 12, difficultyLevel: 1,
    targetSettings: ['HOME', 'SCHOOL_CAFETERIA'],
    materialsNeeded: ['Glass', 'Beverage container'],
    isCriticalSafety: false, communityRelevance: 4, employmentRelevance: 3,
  },
  {
    name: 'Using Toaster',
    description: 'Make toast safely using toaster',
    domain: ILSDomain.COOKING_NUTRITION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Check toaster is unplugged/off', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Insert bread slices', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 3, description: 'Set desired darkness level', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Push lever down', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Wait for toast to pop up', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 6, description: 'Carefully remove toast', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME'],
    materialsNeeded: ['Toaster', 'Bread'],
    isCriticalSafety: true, communityRelevance: 4, employmentRelevance: 3,
  },
  {
    name: 'Making Cereal',
    description: 'Prepare bowl of cereal with milk',
    domain: ILSDomain.COOKING_NUTRITION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Get bowl and spoon', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Get cereal and milk', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Pour cereal into bowl', promptHierarchy: ['INDEPENDENT'] },
      { stepNumber: 4, description: 'Pour milk slowly', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Put items away', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 6, ageAppropriateEnd: 12, difficultyLevel: 1,
    targetSettings: ['HOME'],
    materialsNeeded: ['Bowl', 'Spoon', 'Cereal', 'Milk'],
    isCriticalSafety: false, communityRelevance: 4, employmentRelevance: 2,
  },
  {
    name: 'Reading Nutrition Labels',
    description: 'Understand and compare nutrition information',
    domain: ILSDomain.COOKING_NUTRITION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Locate nutrition facts panel', promptHierarchy: ['GESTURAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Find serving size', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Locate calories per serving', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Identify key nutrients', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['HOME', 'COMMUNITY_STORE'],
    materialsNeeded: ['Food packages with labels'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 3,
  },
  {
    name: 'Food Storage Safety',
    description: 'Store food properly to prevent spoilage',
    domain: ILSDomain.COOKING_NUTRITION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Check if food needs refrigeration', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Use appropriate container', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Label with date', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Place in correct location', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 12, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'COMMUNITY_WORKPLACE'],
    materialsNeeded: ['Storage containers', 'Labels', 'Marker'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Using Stove - Boiling Water',
    description: 'Safely boil water on stovetop',
    domain: ILSDomain.COOKING_NUTRITION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Fill pot with water', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Place pot on burner', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Turn on correct burner', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 4, description: 'Set to high heat', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Watch for boiling', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 6, description: 'Turn off burner when done', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 7, description: 'Use pot holders to move', promptHierarchy: ['VERBAL', 'INDEPENDENT'], criticalStep: true },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['HOME'],
    materialsNeeded: ['Pot', 'Stove', 'Pot holders'],
    isCriticalSafety: true, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Making Simple Salad',
    description: 'Prepare basic green salad',
    domain: ILSDomain.COOKING_NUTRITION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'Wash lettuce thoroughly', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'], criticalStep: true },
      { stepNumber: 2, description: 'Tear or cut lettuce', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Add other vegetables', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Add dressing', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Toss gently', promptHierarchy: ['MODEL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 10, ageAppropriateEnd: 22, difficultyLevel: 2,
    targetSettings: ['HOME', 'COMMUNITY_WORKPLACE'],
    materialsNeeded: ['Lettuce', 'Vegetables', 'Bowl', 'Dressing'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 4,
  },
  {
    name: 'Planning Weekly Meals',
    description: 'Create simple weekly meal plan',
    domain: ILSDomain.COOKING_NUTRITION,
    taskAnalysisSteps: [
      { stepNumber: 1, description: 'List days of week', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
      { stepNumber: 2, description: 'Choose breakfast for each day', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 3, description: 'Choose lunch for each day', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 4, description: 'Choose dinner for each day', promptHierarchy: ['VERBAL', 'INDEPENDENT'] },
      { stepNumber: 5, description: 'Make shopping list from plan', promptHierarchy: ['MODEL', 'VERBAL', 'INDEPENDENT'] },
    ],
    ageAppropriateStart: 14, ageAppropriateEnd: 22, difficultyLevel: 3,
    targetSettings: ['HOME', 'CLASSROOM'],
    materialsNeeded: ['Meal planning template', 'Pen'],
    isCriticalSafety: false, communityRelevance: 5, employmentRelevance: 3,
  },
];

// Export all skills from this file
export const ilsSkillsPart1 = [
  ...moneyManagementSkills,
  ...cookingNutritionSkills,
];

console.log(`ILS Seeds Part 1: ${moneyManagementSkills.length} Money Management + ${cookingNutritionSkills.length} Cooking/Nutrition = ${ilsSkillsPart1.length} total skills`);
