import type { CreateLearnerRequest, CreateLearnerResponse, GenerateBaselineRequest, GenerateBaselineResponse, SubmitBaselineResponsesRequest, SubmitBaselineResponsesResponse, CreateDifficultyProposalRequest, CreateDifficultyProposalResponse, DecideOnDifficultyProposalRequest, DecideOnDifficultyProposalResponse, ListDifficultyProposalsResponse, GenerateLessonPlanRequest, GenerateLessonPlanResponse, GetLearnerResponse, MeResponse } from "./contracts";
import type { ListTenantsResponse, GetTenantConfigResponse, ListDistrictsResponse, ListSchoolsResponse, ListRoleAssignmentsResponse } from "./admin-contracts";
import type { GetCaregiverLearnerOverviewResponse, ListNotificationsResponse, MarkNotificationReadResponse } from "./caregiver-contracts";
import type { GetLearnerAnalyticsResponse, GetTenantAnalyticsResponse } from "./analytics-contracts";
import type { GetTodaySessionResponse, StartSessionRequest, StartSessionResponse, UpdateActivityStatusRequest, UpdateActivityStatusResponse, PlanSessionRequest, PlanSessionResponse } from "./session-contracts";
import type { ListCurriculumTopicsResponse, CreateCurriculumTopicRequest, CreateCurriculumTopicResponse, UpdateCurriculumTopicRequest, UpdateCurriculumTopicResponse, ListContentItemsResponse, CreateContentItemRequest, CreateContentItemResponse, UpdateContentItemRequest, UpdateContentItemResponse, GenerateDraftContentRequest, GenerateDraftContentResponse } from "./content-contracts";
import type { RecordFeedbackRequest, RecordFeedbackResponse, AggregateFeedbackResponse } from "./feedback-contracts";
import type { GetTenantLimitsResponse, UpdateTenantLimitsRequest, UpdateTenantLimitsResponse, ListAuditLogsResponse, ListTenantUsageResponse } from "./governance-contracts";
export declare class AivoApiClient {
    private baseUrl;
    private getToken?;
    constructor(baseUrl: string, getToken?: (() => Promise<string | null>) | undefined);
    private request;
    me(): Promise<MeResponse>;
    createLearner(body: CreateLearnerRequest): Promise<CreateLearnerResponse>;
    getLearner(learnerId: string): Promise<GetLearnerResponse>;
    generateBaseline(body: GenerateBaselineRequest): Promise<GenerateBaselineResponse>;
    submitBaselineResponses(body: SubmitBaselineResponsesRequest): Promise<SubmitBaselineResponsesResponse>;
    createDifficultyProposal(body: CreateDifficultyProposalRequest): Promise<CreateDifficultyProposalResponse>;
    decideOnDifficultyProposal(body: DecideOnDifficultyProposalRequest): Promise<DecideOnDifficultyProposalResponse>;
    listDifficultyProposals(learnerId: string): Promise<ListDifficultyProposalsResponse>;
    generateLessonPlan(body: GenerateLessonPlanRequest): Promise<GenerateLessonPlanResponse>;
    listTenants(): Promise<ListTenantsResponse>;
    getTenantConfig(tenantId: string): Promise<GetTenantConfigResponse>;
    listDistricts(tenantId: string): Promise<ListDistrictsResponse>;
    listSchools(tenantId: string, districtId?: string): Promise<ListSchoolsResponse>;
    listRoleAssignments(tenantId: string): Promise<ListRoleAssignmentsResponse>;
    getTenantLimits(tenantId: string): Promise<GetTenantLimitsResponse>;
    updateTenantLimits(tenantId: string, body: UpdateTenantLimitsRequest): Promise<UpdateTenantLimitsResponse>;
    listAuditLogs(tenantId: string): Promise<ListAuditLogsResponse>;
    listTenantUsage(tenantId: string): Promise<ListTenantUsageResponse>;
    getTodaySession(learnerId: string, subject: string): Promise<GetTodaySessionResponse>;
    startSession(body: StartSessionRequest): Promise<StartSessionResponse>;
    updateActivityStatus(body: UpdateActivityStatusRequest): Promise<UpdateActivityStatusResponse>;
    planSession(body: PlanSessionRequest): Promise<PlanSessionResponse>;
    getCaregiverLearnerOverview(learnerId: string): Promise<GetCaregiverLearnerOverviewResponse>;
    listNotifications(): Promise<ListNotificationsResponse>;
    markNotificationRead(notificationId: string): Promise<MarkNotificationReadResponse>;
    respondToDifficultyProposal(body: {
        proposalId: string;
        decision: "approve" | "reject";
    }): Promise<DecideOnDifficultyProposalResponse>;
    getLearnerAnalytics(learnerId: string): Promise<GetLearnerAnalyticsResponse>;
    getTenantAnalytics(tenantId: string): Promise<GetTenantAnalyticsResponse>;
    listCurriculumTopics(): Promise<ListCurriculumTopicsResponse>;
    createCurriculumTopic(body: CreateCurriculumTopicRequest): Promise<CreateCurriculumTopicResponse>;
    updateCurriculumTopic(body: UpdateCurriculumTopicRequest): Promise<UpdateCurriculumTopicResponse>;
    listContentItems(topicId: string): Promise<ListContentItemsResponse>;
    createContentItem(body: CreateContentItemRequest): Promise<CreateContentItemResponse>;
    updateContentItem(body: UpdateContentItemRequest): Promise<UpdateContentItemResponse>;
    generateDraftContent(body: GenerateDraftContentRequest): Promise<GenerateDraftContentResponse>;
    recordFeedback(body: RecordFeedbackRequest): Promise<RecordFeedbackResponse>;
    getFeedbackAggregate(targetType: string, targetId: string): Promise<AggregateFeedbackResponse>;
}
