export declare function listCurriculumTopicsForTenant(tenantId: string): Promise<{
    tenantId: string;
    subject: string;
    id: string;
    region: string;
    createdAt: Date;
    updatedAt: Date;
    title: string;
    grade: number;
    standard: string;
    code: string | null;
    description: string | null;
}[]>;
export declare function createCurriculumTopic(args: {
    tenantId: string;
    subject: string;
    grade: number;
    region: string;
    standard: string;
    code?: string;
    title: string;
    description?: string;
}): Promise<{
    tenantId: string;
    subject: string;
    id: string;
    region: string;
    createdAt: Date;
    updatedAt: Date;
    title: string;
    grade: number;
    standard: string;
    code: string | null;
    description: string | null;
}>;
export declare function updateCurriculumTopic(id: string, updates: {
    title?: string;
    description?: string;
    code?: string | null;
}): Promise<{
    tenantId: string;
    subject: string;
    id: string;
    region: string;
    createdAt: Date;
    updatedAt: Date;
    title: string;
    grade: number;
    standard: string;
    code: string | null;
    description: string | null;
}>;
export declare function listContentItemsForTopic(topicId: string): Promise<{
    tenantId: string;
    subject: string;
    topicId: string;
    id: string;
    type: string;
    createdAt: Date;
    status: string;
    updatedAt: Date;
    title: string;
    body: string;
    grade: number;
    questionFormat: string | null;
    options: import("@prisma/client/runtime/library").JsonValue | null;
    correctAnswer: string | null;
    accessibilityNotes: string | null;
    createdByUserId: string;
    aiGenerated: boolean;
    aiModel: string | null;
}[]>;
export declare function createContentItem(args: {
    tenantId: string;
    topicId: string;
    subject: string;
    grade: number;
    type: string;
    title: string;
    body: string;
    questionFormat?: string;
    options?: Record<string, any>;
    correctAnswer?: string;
    accessibilityNotes?: string;
    status: string;
    createdByUserId: string;
    aiGenerated?: boolean;
    aiModel?: string;
}): Promise<{
    tenantId: string;
    subject: string;
    topicId: string;
    id: string;
    type: string;
    createdAt: Date;
    status: string;
    updatedAt: Date;
    title: string;
    body: string;
    grade: number;
    questionFormat: string | null;
    options: import("@prisma/client/runtime/library").JsonValue | null;
    correctAnswer: string | null;
    accessibilityNotes: string | null;
    createdByUserId: string;
    aiGenerated: boolean;
    aiModel: string | null;
}>;
export declare function updateContentItem(id: string, updates: {
    title?: string;
    body?: string;
    status?: string;
    questionFormat?: string | null;
    options?: Record<string, any>;
    correctAnswer?: string | null;
    accessibilityNotes?: string | null;
}): Promise<{
    tenantId: string;
    subject: string;
    topicId: string;
    id: string;
    type: string;
    createdAt: Date;
    status: string;
    updatedAt: Date;
    title: string;
    body: string;
    grade: number;
    questionFormat: string | null;
    options: import("@prisma/client/runtime/library").JsonValue | null;
    correctAnswer: string | null;
    accessibilityNotes: string | null;
    createdByUserId: string;
    aiGenerated: boolean;
    aiModel: string | null;
}>;
